apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bike-lgbm
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa
    ### START CONF HERE
    canaryTrafficPercent: 30
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/6/1bde08d49b9d46c186abe32ee14755db/artifacts/lgbm-bike"
    ### END CONF HERE
