apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph 
metadata: 
  name: my-graph2
  namespace: kserve-inference
spec: 
  nodes: 
    ### START CONF HERE
    root:
      routerType: Switch
      steps:
        - condition: "[@this].#(modelType==\"lgbm\")"
          nodeName: lgbmEnsemble
        - condition: "[@this].#(modelType==\"xgb\")"
          nodeName: xgbEnsemble
    lgbmEnsemble:
      routerType: Ensemble
      steps:
        - serviceName: bike-lgbm-1
        - serviceName: bike-lgbm-2
    xgbEnsemble:
      routerType: Ensemble
      steps:
        - serviceName: bike-xgb-1
        - serviceName: bike-xgb-2
    ### END CONF HERE
